name: Bug Report
description: File a bug report to help improve Sunrise further
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["WushR00M-Studios/1"]
type: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "Something happened..."
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What version of Sunrise are you playing?
      value: "v2026.5.0"
    validations:
      required: true
  - type: dropdown
    id: compatl
    attributes:
      label: What system are you running Sunrise on?
      multiple: false
      options:
        - Windows
        - MacOS
        - Linux / SteamOS
  - type: dropdown
    id: browsers
    attributes:
      label: If you are running Sunrise through Linux / SteamOS, what compatibility layer are you using?
      multiple: false
      options:
        - Proton (Steam)
        - Wine
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: upload
    id: screenshots
    attributes:
      label: Upload screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
